name: C++ Build and Test

on:
  push:
    branches: [ main, cpp-multithreading ]
  pull_request:
    branches: [ main, cpp-multithreading ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install clang-format
      - name: Build
        run: |
          make clean
          make
      - name: Run tests
        run: |
          make test
      - name: Check formatting
        run: |
          clang-format --dry-run --Werror src/*.cpp include/*.hpp tests/*.cpp
