name: C++ Build and Test

on:
  push:
    branches: [ main, main-cpp ]
  pull_request:
    branches: [ main, main-cpp ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew install clang-format
          brew install cmake
      - name: Build GoogleTest
        run: |
          cd third_party/googletest
          cmake -S . -B build
          cmake --build build
      - name: Build
        run: |
          make clean
          make
      - name: Run tests
        run: |
          make test
      - name: Check formatting
        run: |
          clang-format --dry-run --Werror src/*.cpp include/*.hpp tests/*.cpp
